### PR TITLE
Improve _.compact alternative

### PR DESCRIPTION
**Pull request by rubennorte**
Instead of defining a new arrow function, the Boolean function can be used to cast values and properly filter all falsy values.

### CODE REVIEW

**Comment by kirillrogovoy** [comment]
Wow! It's cool, but really unreadable :) I mean I wouldn't understand this in 15 seconds without description.

**Comment by rubennorte** [comment]
Well, I suppose that's kind of subjective. Maybe the current form is easier to understand, but I wanted to contribute with an even shorter version. Feel free to discard the PR if you're not convinced about it.

**Comment by fson** [comment]
I find it quite easy to read, kind of similar to how you can do `filter(bool, some_list)` in Python :)

@rubennorte since your example is compatible with ES5.1, and some people might prefer `!!`, maybe we could keep both and just label them accordingly?

ES5.1

``` javascript
array.filter(Boolean)
```

ES2015

``` javascript
array.filter(x => !!x)
```

**Comment by fson** [comment]
Added in https://github.com/reindexio/youmightnotneedunderscore/commit/5db90a1c61d0e1fd754a9166040fa83d166cd555. Thanks @rubennorte!

**Comment by rubennorte** [comment]
Thank you for adding it so fast! ;)

**Pull request closed without merging**
